# THIS FILE HAS AS TITLE NOW ?

In [2]:
import numpy as np
import pyvista as pv

In [7]:
n = 9

In [8]:
dem = np.zeros(shape=(n,n))

In [25]:
np.fill_diagonal(dem[:,8:],n-8)

In [26]:
dem

array([[9., 8., 7., 6., 5., 4., 3., 2., 1.],
       [0., 9., 8., 7., 6., 5., 4., 3., 2.],
       [0., 0., 9., 8., 7., 6., 5., 4., 3.],
       [0., 0., 0., 9., 8., 7., 6., 5., 4.],
       [0., 0., 0., 0., 9., 8., 7., 6., 5.],
       [0., 0., 0., 0., 0., 9., 8., 7., 6.],
       [0., 0., 0., 0., 0., 0., 9., 8., 7.],
       [0., 0., 0., 0., 0., 0., 0., 9., 8.],
       [0., 0., 0., 0., 0., 0., 0., 0., 9.]])

In [28]:
ttt = dem.T + dem

In [29]:
ttt

array([[18.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 8., 18.,  8.,  7.,  6.,  5.,  4.,  3.,  2.],
       [ 7.,  8., 18.,  8.,  7.,  6.,  5.,  4.,  3.],
       [ 6.,  7.,  8., 18.,  8.,  7.,  6.,  5.,  4.],
       [ 5.,  6.,  7.,  8., 18.,  8.,  7.,  6.,  5.],
       [ 4.,  5.,  6.,  7.,  8., 18.,  8.,  7.,  6.],
       [ 3.,  4.,  5.,  6.,  7.,  8., 18.,  8.,  7.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8., 18.,  8.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 18.]])

In [30]:
ttt[0:n,0:n]

array([[18.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 8., 18.,  8.,  7.,  6.,  5.,  4.,  3.,  2.],
       [ 7.,  8., 18.,  8.,  7.,  6.,  5.,  4.,  3.],
       [ 6.,  7.,  8., 18.,  8.,  7.,  6.,  5.,  4.],
       [ 5.,  6.,  7.,  8., 18.,  8.,  7.,  6.,  5.],
       [ 4.,  5.,  6.,  7.,  8., 18.,  8.,  7.,  6.],
       [ 3.,  4.,  5.,  6.,  7.,  8., 18.,  8.,  7.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8., 18.,  8.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 18.]])

In [34]:
np.fill_diagonal(ttt,9)

In [35]:
ttt

array([[9., 8., 7., 6., 5., 4., 3., 2., 1.],
       [8., 9., 8., 7., 6., 5., 4., 3., 2.],
       [7., 8., 9., 8., 7., 6., 5., 4., 3.],
       [6., 7., 8., 9., 8., 7., 6., 5., 4.],
       [5., 6., 7., 8., 9., 8., 7., 6., 5.],
       [4., 5., 6., 7., 8., 9., 8., 7., 6.],
       [3., 4., 5., 6., 7., 8., 9., 8., 7.],
       [2., 3., 4., 5., 6., 7., 8., 9., 8.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [42]:
x = np.arange(9)

In [43]:
y = np.arange(9)

In [44]:
xx,yy = np.meshgrid(x,y)

In [70]:
points = np.c_[xx.reshape(-1),yy.reshape(-1),ttt.reshape(-1)]

In [62]:
ttt_flip = np.fliplr(ttt)

In [71]:
cloud = pv.PolyData(points)

In [65]:
cloud.plot(point_size=2)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

In [72]:
surf = cloud.delaunay_3d()

In [73]:
surf.plot(show_edges=True)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)